### ISSUE TITLE
Spatio-temporal prediction

### ISSUE THREAD

**Issue by meteoDaniel** [gitbooo/CrossViVit#11]
Awesome work and it is really interesting that the model seems to learn physics ? Or do you think the good results are because of using Locations in the Center of the satellite Images ? 

Nevertheless, i asked myself whether it is possible to generate predictions for locations without observed GHI? 

E.g. providing the latest satellite images and all available observations and Receive a prediction for and other Location in the area ? 

Thanks and best regards!

**Comment by jaggbow** [comment]
Hi @meteoDaniel !
 The architecture was designed to produce predictions for one location efficiently. You can predict at multiple locations but it will be slow if you try to predict at all possible locations in the satellite area. Unfortunately, you do need past GHI observations, that's how the model was trained. 

If you don't want to use past observations, then you'll need to retrain the model with that in mind.

I hope that answers your questions and sorry for missing the issue !
