### ISSUE TITLE
What services do you suggest to use for training in case I do not have 2 RTX8000 GPUs?

### ISSUE THREAD

**Issue by deep404** [gitbooo/CrossViVit#3]
I tried to minimize the batch to 1 and train locally where I have a 3070 8Gb, but without any success

**Comment by deep404** [comment]
I tried to minimize the batch to 1 and train locally where I have a 3070 8Gb, but without any success

**Comment by jaggbow** [comment]
I am afraid that 8GB might be a bit too low. For reference, we used two RTX8000 GPUs which have 48GB of VRAM each to run a batch size of 10. You can find the checkpoints for the model for inference in our [release](https://github.com/gitbooo/CrossViVit/releases/tag/0.1.0).
