### ISSUE TITLE
Can you please share the weight of the model and a testing script?

### ISSUE THREAD

**Issue by deep404** [gitbooo/CrossViVit#4]
Unfortunately, to train the model, it is required expensive hardware RTX8000 (6000$ + per one), but you have trained your model on 2. Can you please share the weights which you have trained?

Also, could you please share a testing script, where the parameters are, for example, 1-2, or 7 days historical time series, 1-2 or 7 days satellite images and the model?

**Comment by jaggbow** [comment]
We will shortly release the parameters and create an eval script. We will also share training scripts and detailed guidance on how to use them. Thanks for the issue !

**Comment by deep404** [comment]
Great, I'm looking forward to it :))

**Comment by jaggbow** [comment]
Hey, we added the checkpoints to the models that you can find in our [release ](https://github.com/gitbooo/CrossViVit/releases/tag/0.1.0)
